# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kandarp Khandwala
description: > # this means to ignore newlines until "baseurl:"
  Kandarp Khandwala's portfolio (and personal site). I'm all about user experience (UX), information visualization and their intersection with data analytics.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.kandarp.xyz" # the base hostname & protocol for your site
github_username:  kandarpksk

# Build settings
markdown: kramdown

# Google services
google_analytics: UA-84595976-1