# Site settings
title:          Kandarp Khandwala
description:    "Kandarp Khandwala's personal site."
url:            "http://kandarp.xyz"

# # Author
# author:
#   name:         Kandarp Khandwala
#   url:          http://kandarp.xyz
#   email:        see@home.page

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       7
